services:
  backend:
    build: ./backend
    image: bombparty-backend
    container_name: bombparty-backend
    restart: always
    environment:
      - PORT=3001
      - CORS_ORIGIN=https://kelimebombasi.com,https://www.kelimebombasi.com
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    image: bombparty-frontend
    container_name: bombparty-frontend
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - backend
